global:
  resolve_timeout: 1m
route:
  receiver: 'slack'
  routes:
  - match_re:
      alertname: 'Onf.*'
    receiver: 'webhook'
    continue: true
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h
  group_by: [alertname, instance]
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname

receivers:
- name: 'slack'
  slack_configs:
  - send_resolved: true
    api_url: 'https://hooks.slack.com/services/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'
    channel: '#monitoring-alerts'

- name: 'webhook'
  webhook_configs:
  - send_resolved: true
    url: 'http://localhost:9333/'
