apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana-rc
spec:
  replicas: 1
  selector:
    app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      nodeSelector:
        monitoring: telemetry
      containers:
      - name: grafana
        image: grafana/grafana:5.2.2
        env:
        - name: ADMIN_USER
          value: "admin"
        - name: ADMIN_PASS
          value: "admin"
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/grafana/
          name: grafana-volume
      volumes:
      - name: grafana-volume
        persistentVolumeClaim:
          claimName: telemetry-pvc

